add the the project. Task1
L00zeritt0/altexsoft-lab-2020 pull request #1
Opened 2020-07-31 17:18 UTC by L00zeritt0

2020-08-03 12:43 UTC, alex-geraschenko requested changes
Постарайтесь разнести классы так, что за каждую задачу в задании отвечал отдельный класс в соответствии с принципами SOLID

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/DirInformer.cs
> +                if (!value.Equals(""))
Лучше использовать `string.IsNullOrEmpty`

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/TextEditer.cs
> +                if (!value.Equals(""))
Лучше использовать `string.IsNullOrEmpty`

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/TextFileReader.cs
> +                using (StreamReader reader = new StreamReader(path))
Вместо стрима можно использовать статические методы у `File`

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/TextEditer.cs
> +                StringBuilder sb = new StringBuilder(text);
Здесь `StringBuilder` избыточен

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/TextEditer.cs
> +                Console.Write(collection[i].Value + ", ");
Обратите внимание на `string.Join`

2020-08-03 12:43 UTC, alex-geraschenko commented on MyApp/MyApp/BL/TextEditer.cs
> +            Char[] charArr = word.ToCharArray();
Этот метод можно заменить одной строкой

2020-08-03 15:32 UTC, L00zeritt0 commented
1 класс - 1 задача.

Имеется ввиду, к примеру:
   - Удалить в тексте указанное слово/символ - отдельный класс;
   - вывести к-во слов в тексте - отдельный класс;
   - вывести каждое 10е слово - отдельный класс;
   - и так далее;

Правильно понял?

пн, 3 авг. 2020 г., 15:44 Alex Geraschenko <notifications@github.com>:

> *@alex-geraschenko* requested changes on this pull request.
>
> Постарайтесь разнести классы так, что за каждую задачу в задании отвечал
> отдельный класс в соответствии с принципами SOLID
> ------------------------------
>
> In MyApp/MyApp/BL/DirInformer.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464383230>
> :
>
> > +    class DirInformer: IDirInformer
>
> +    {
>
> +        private String path;
>
> +        private DirectoryInfo di;
>
> +        private DirectoryInfo[] diArr;
>
> +        private FileInfo[] fiArr;
>
> +
>
> +        public String Path
>
> +        {
>
> +            get
>
> +            {
>
> +                return path;
>
> +            }
>
> +            set
>
> +            {
>
> +                if (!value.Equals(""))
>
>
> Лучше использовать string.IsNullOrEmpty
> ------------------------------
>
> In MyApp/MyApp/BL/TextEditer.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464384661>
> :
>
> > +﻿using System;
>
> +using System.Runtime.InteropServices.WindowsRuntime;
>
> +using System.Text;
>
> +using System.Text.RegularExpressions;
>
> +
>
> +namespace MyApp.BL
>
> +{
>
> +    class TextEditer : ITextEditable
>
> +    {
>
> +        private String text;
>
> +        private String word;
>
> +        public String Text
>
> +        {
>
> +            set
>
> +            {
>
> +                if (!value.Equals(""))
>
>
> Лучше использовать string.IsNullOrEmpty
> ------------------------------
>
> In MyApp/MyApp/BL/TextFileReader.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464385287>
> :
>
> > +                else
>
> +                {
>
> +                    Console.WriteLine("Check the path. It's empty.");
>
> +                    throw new NullReferenceException();
>
> +                }
>
> +            }
>
> +        }
>
> +        public TextFileReader(String path)
>
> +        {
>
> +            Path = path;
>
> +        }
>
> +        public String ReadText()
>
> +        {
>
> +            try
>
> +            {
>
> +                using (StreamReader reader = new StreamReader(path))
>
>
> Вместо стрима можно использовать статические методы у File
> ------------------------------
>
> In MyApp/MyApp/BL/TextEditer.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464385914>
> :
>
> > +                else
>
> +                {
>
> +                    Console.WriteLine("Check your word. It's empty.");
>
> +                    throw new NullReferenceException();
>
> +                }
>
> +            }
>
> +        }
>
> +        public TextEditer(String text)
>
> +        {
>
> +            Text = text;
>
> +        }
>
> +        public String EditText()
>
> +        {
>
> +            if (text.Contains(word))
>
> +            {
>
> +                StringBuilder sb = new StringBuilder(text);
>
>
> Здесь StringBuilder избыточен
> ------------------------------
>
> In MyApp/MyApp/BL/TextEditer.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464386196>
> :
>
> > +                return "\nCurrent word/char doesn't exist in the text. Please, try again with another word/char.";
>
> +            }
>
> +
>
> +        }
>
> +        public int WordCounter()
>
> +        {
>
> +            Console.WriteLine();
>
> +            return TakeWordsCollection(text).Count;
>
> +        }
>
> +        public void EveryTenthWord()
>
> +        {
>
> +            MatchCollection collection = TakeWordsCollection(text);
>
> +            Console.WriteLine();
>
> +            for (int i = 9; i < collection.Count; i+=10)
>
> +            {
>
> +                Console.Write(collection[i].Value + ", ");
>
>
> Обратите внимание на string.Join
> ------------------------------
>
> In MyApp/MyApp/BL/TextEditer.cs
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#discussion_r464386873>
> :
>
> > +            return "\n" + sentence.ToString();
>
> +
>
> +        }
>
> +        private MatchCollection TakeWordsCollection(String text)
>
> +        {
>
> +            Regex regex = new Regex(@"[a-z]+'[a-z]+|[a-z]{2,}", RegexOptions.IgnoreCase);
>
> +            return regex.Matches(text);
>
> +        }
>
> +        private String[] TakeSentencesCollection(String text)
>
> +        {
>
> +            Regex regex = new Regex(@"[.]+\s+", RegexOptions.IgnoreCase);
>
> +            return regex.Split(text);
>
> +        }
>
> +        private String WordReverse(String word)
>
> +        {
>
> +            Char[] charArr = word.ToCharArray();
>
>
> Этот метод можно заменить одной строкой
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/L00zeritt0/altexsoft-lab-2020/pull/1#pullrequestreview-459987214>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACZKDFTYMYWW3TMCZVYP2MTR62WJ3ANCNFSM4PQS6BKQ>
> .
>

2020-08-03 17:19 UTC, alex-geraschenko commented
> Правильно понял?

Да

2020-08-12 15:45 UTC, alex-geraschenko approved these changes
Выглядит хорошо. Можно мержить

2020-08-19 14:03 UTC, merged