add task2
L00zeritt0/altexsoft-lab-2020 pull request #2
Opened 2020-08-19 14:09 UTC by L00zeritt0

2020-08-19 20:21 UTC, serhii-shkodenko requested changes

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        public String Path
Данное публичное ствойство Вы используете только в рамках этого класса, следовательно лучше воспользоваться приватным полем.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        public String Path
Классическая реализация паттерна репозиторий подразумевает только оперирование данными, а у Вас она  знает об источнике данных слишком много. Обратите внимание на Single Responsibility принцип.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +            Path = path;
Если Вы инициализируете свойство или поле из конструктора и далее не планируете его изменять, следует подумать, как избежать непреднамеренного их измененния. Почитайте о модификаторах доступа для геттеров и сеттеров свойств, а также модификаторе readonly для полей.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        private String path;
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +    public class JSONRepository<T>: IRepository<T>
Обратите внимание на наименование типов. Использование заглавных букв регламентирует это правило https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1709?view=vs-2019

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        public JSONRepository(String path)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +                    throw new ArgumentNullException("The path is empty or wrong.");
Здесь Вы используете одну из перегрузок конструктора, которая требует, что в качестве аргумента в конструктор будет передано имя аргумента, значение которого является `null`. А Вы передаете сообщение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +                    throw new ArgumentNullException("The path is empty or wrong.");
Почему Вы проверяете существование файла, а кидаете ArgumentNullException? Здесь нужно другое исключение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/IRepository.cs
> +        /// <returns></returns>
Тег `returns` пустой. Либо удалите, либо наполните полезным содержимым.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        /// <returns></returns>
Тег `returns` пустой. Либо удалите, либо наполните полезным содержимым.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        /// <param name="list"></param>
Отсутствует описание параметра. 
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/param

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/IRepository.cs
> +        /// <param name="list"></param>
Отсутствует описание параметра. 
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/param

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +            String pathRecipes = @"C:\Users\L00zeritt0\Desktop\AltexSoft\altexsoft-lab-2020\RecipeBook\recipes.json";
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +                    else if (!Int32.TryParse(temp, out category))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                String temp = Console.ReadLine();
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                else if (!Int32.TryParse(temp, out result))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +        public void AddRecipe(String name, String category, List<RecipeIngredient> ingredients, List<CookingStep> steps)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        private String cookingStepDescription;
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/Interfaces/IRecipeControllerInterface.cs
> +        void AddRecipe(String name, String category, List<RecipeIngredient> ingredients, List<CookingStep> steps);
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/FoodProductController.cs
> +        public void AddFoodProduct(String name)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/CategoryController.cs
> +        public CategoryController(String path)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/CategoryController.cs
> +            ListOfCatigories = data.GetAllItems();
Общепринятым является подход, когда в контроллере определяется метод, который уже затем использует репозиторий.  Если Вы храните данные в контроллере, Вы нарушаете Single Responsibility принцип.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/FoodProductController.cs
> +        public FoodProductController(String path)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/FoodProductController.cs
> +            ListOfFoods = data.GetAllItems();
Общепринятым является подход, когда в контроллере определяется метод, который уже использует репозиторий.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/FoodProductController.cs
> +        /// <param name="name"></param>
Отсутствует описание для параметра.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +        /// <param name="name"></param>
Отсутствуют описания для параметров.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +        public RecipeController(String path)
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +            ListOfRecipes = data.GetAllItems();
Общепринятым является подход, когда в контроллере определяется метод, который уже затем использует репозиторий. Подумайте, почему хранение данных в контроллере нарушет Single Responsibility принцип.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +        /// <returns></returns>
Отсутствует описание для параметра. Пустой тег `<returns/>`

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +                    select r).ToList<Recipe>();
Рассмотрите возможность выноса данной логики в репозиторий.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +                if (String.IsNullOrWhiteSpace(value))
Общепринятым является использование псевдонима для простых типов, если они есть.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +                    throw new ArgumentNullException("Cooking step can't be empty.");
Здесь Вы используете одну из перегрузок конструктора, которая требует, что в качестве аргумента в конструктор будет передано имя аргумента, значение которого является `null`. А Вы передаете сообщение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        /// <param name="description"></param>
Отсутствует описание для параметра.
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/param

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        public String CookingStepDescription
Вы не используете это свойство нигде, кроме данного класса. Стоит подумать над заменой его на приватное поле.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +                    throw new ArgumentNullException("Name of food product can't be empty. Please, chech it");
Здесь Вы используете одну из перегрузок конструктора, которая требует, что в качестве аргумента в конструктор будет передано имя аргумента, значение которого является `null`. А Вы передаете сообщение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        private String name;
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        public String Name
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +                if (String.IsNullOrWhiteSpace(value))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        /// <param name="name"></param>
Отсутствует описание для параметра.
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/param

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        public FoodProduct(String name)
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        private String recipeName;
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +                if (String.IsNullOrWhiteSpace(value))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        public String RecipeName
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +                    throw new ArgumentNullException("Recipe name can't be empty.");
Здесь Вы используете одну из перегрузок конструктора, которая требует, что в качестве аргумента в конструктор будет передано имя аргумента, значение которого является `null`. А Вы передаете сообщение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        /// <param name="steps"></param>
Отсутствуют описания для параметров.
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/xmldoc/param

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        public Recipe(String name,
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        /// Class constructor.
Рассмотрите возможность задать более значимое описание.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        public CookingStep(String description)
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +            RecipeCategory = new RecipeBookCategory(categoryName);
Почему бы не передавать сразу готовый объект `RecipeBookCategory`?

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        public Recipe(String name,
Рассмотрите необходимость данного конструктора. У Вас есть публичные свойства.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        public FoodProduct(String name)
У вас есть публичные свойства. Подумайте, нужен ли Вам этот конструктор.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        public CookingStep(String description)
У вас есть публичные свойства. Подумайте, нужен ли Вам этот конструктор.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +        public RecipeBookCategory(String name)
У вас есть публичные свойства. Подумайте, нужен ли Вам этот конструктор.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +        public String CategoryName
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +        /// <param name="name"></param>
Пропустили описание для параметра.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +        /// Class constructor
Рассмотрите целесообразность существования данного комментария.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +                    throw new ArgumentNullException("Category must to have a name.");
Здесь Вы используете одну из перегрузок конструктора, которая требует, что в качестве аргумента в конструктор будет передано имя аргумента, значение которого является `null`. А Вы передаете сообщение.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +                if (String.IsNullOrWhiteSpace(value))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +        /// <param name="weight"></param>
Пропущены описания для параметров.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +        /// Constructor of RecipeIngredient class
Рассмотрите целесообразность данного комментария.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +        public RecipeIngredient(String name, int weight)
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +            FoodProduct = new FoodProduct(name);
Почему бы сразу не передавать в конструктор объект типа `FoodProduct`?

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +        public RecipeIngredient(String name, int weight)
Подумайте, нужен ли Вам этот конструктор, ведь Вы определили публичные свойства.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +            return $"{FoodProduct} ({WeightOfFoodProduct} gm)";
А если я буду использовать молоко?

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        private String categoryName;
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        /// </summary>
Обратите внимание, к каким типам в Вашем коде относятся XML комментарии, а к каким нет. Возможно, для Вашия целей подойдут регионы `region`
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +            foodProductController = new FoodProductController(pathFoods);
Рассмотрите возможность объявления всех трех приватных полей только для чтения.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        /// <param name="i"></param>
Заполните описание для параметра.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        /// <param name="i"></param>
Заполните описание для параметра.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        public void FoodProductAdder()
Имена методов в C# принято давать в глагольной форме 
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        public void RecipeAdder()
Имена методов в C# принято давать в глагольной форме
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/RecipeController.cs
> +        public void AddRecipe(String name, String category, List<RecipeIngredient> ingredients, List<CookingStep> steps)
Имя метода подразумевает, что в качестве аргумента ему будет передан объект типа `Recipe`. Попробуйте реализовать это поведение. Пока Ваш метод не только добавляет новый рецепт, но и создает соответсвующий объект.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                else if (!Int32.TryParse(temp, out result))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                if (temp.Equals("q"))
Подумайте, как сократить дублирование кода.

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +            //Temporary variables
Почитайте про регионы, возможно они лучше подойдут для Ваших целей
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region

2020-08-19 20:21 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +                    else if (!Int32.TryParse(temp, out result))
Общепринятым является использование псевдонима для простых типов, если они есть.
https://stackoverflow.com/questions/62503/should-i-use-int-or-int32

2020-08-21 16:53 UTC, alex-geraschenko requested changes

2020-08-21 16:53 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +            String pathRecipes = @"C:\Users\L00zeritt0\Desktop\AltexSoft\altexsoft-lab-2020\RecipeBook\recipes.json";
Пути к файлам не должны быть жестко прописаны в коде, иначе этот код не будет работать на другом компьютере

2020-08-25 19:28 UTC, serhii-shkodenko requested changes

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        /// </summary>
Некорректное использование XML documentation comments. Почитайте про регионы https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region

Обратите внимание на это в других местах Вашего кода.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        public ResourceManager addStepStrings = new ResourceManager("RecipeBook.ConsoleInterface.AddStepStrings", typeof(Manager).Assembly);
Вы используете эти переменные только локально. Зачем тогда модификтор public?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +        public RecipeIngredient() { }
Вам не нужно явным образом задавать дефолтный конструктор без параметров, если нет хотя бы еще одного параметрического.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeIngredient.cs
> +                if (String.IsNullOrWhiteSpace(value))
Если используете псевдонимы для типов, делайте это везде.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/RecipeBookCategory.cs
> +        public RecipeBookCategory() { }
Зачем здесь дефолтный конструктор?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        public Recipe() { }
Зачем здесь дефолтный конструктор?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/FoodProduct.cs
> +        public FoodProduct() { }
Зачем здесь дефолтный конструктор?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/CookingStep.cs
> +        public CookingStep() { }
Зачем здесь дефолтный конструктор?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/Controller.cs
> +        private IRepository<T> data;
Здесь можно добавить readonly модификатор.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Controller/Controller.cs
> +        public List<T> GetAllItems()
Вы здесь применяете `List`, при этом возвращаемые данные служат только для вывода в консоль. Никаких операций со списком не проводится. Посмотрите в сторону IEnumerable.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        public string RecipeName
Если класс у Вас называется `Recipe`, необязательно добавлять это префиксом к именам всех свойств и полей. Подумайте, как это выглядит: `Recipe.RecipeIngredients`.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                                    select r).ToList<Recipe>();
Неэффективный запрос. Для фильтрации списка по полю, Вы делаете два обращения к источнику данных. Подумайте, может стоит передавать не индекс категории, а имя категории?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                recipe.RecipeSteps = steps;
А что здесь может случиться, что вы присваивание оборачивайете в `try-catch`?

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                if (result > 0 || result <= foodProductController.GetAllItems().Count)
Если Вы хотели проверить, что введенное число находится в определенных пределах, то условный оператор логического или здесь не подойдет.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                if (result > 0 || result <= categoryController.GetAllItems().Count)
Если Вы хотели проверить, что введенное число находится в определенных пределах, то условный оператор логического или здесь не подойдет.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +        protected List<T> listOfItems;
- Почитайте как именовать свойства. 
- Посмотрите примеры кода по паттерну Repository, предполагается ли непосредственное хранение данных.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.DL/JSONRepository.cs
> +            listOfItems = (List<T>)GetAllItems();
Почитайте про гайдлайны касательно конструкторов https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/constructor

Этот код получения данных лучше вынести в соответстующий метод.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +                catch (Exception e)
В слвучае возникновения исключения, выход из цикла не происходит.

2020-08-25 19:28 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +            #endregion
Зачем этот блок кода? Если он не нужен, удалите его.

2020-08-25 19:46 UTC, serhii-shkodenko requested changes

2020-08-25 19:46 UTC, serhii-shkodenko commented on RecipeBook/RecipeBook.ConsoleInterface/Program.cs
> +                string pathRecipes = Console.ReadLine();
Почитайте про `System.AppDomain.CurrentDomain.BaseDirectory`.

2020-08-28 16:47 UTC, alex-geraschenko requested changes
1. В каждую модель я бы еще добавил свойство `Id` и в моделях, где есть зависимости от других моделей, добавил бы свойство, которое будет содержать не всю зависимость, а только ее айдишник. При этом на свойство зависимости повесил бы атрибут `JsonIgnore`
2. Я не нашел, как у Вас реализованы подкатегории

2020-08-28 16:49 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        public readonly IController<RecipeBookCategory> categoryController;
Почему публичный?

2020-08-28 16:50 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +        public void ShowRecipeList(string categpry)
Опечатка в имени параметра

2020-08-28 16:52 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                temp = Console.ReadLine();
Попробуйте `System.ConsoleKey`

2020-08-28 16:53 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                    temp = (foodProductController.GetAllItems()).ToList()[result - 1].Name;
У Вас дублирование чтения продуктов.

2020-08-28 16:54 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +                    temp = (foodProductController.GetAllItems()).ToList()[result - 1].Name;
Вместо использования `[result-1]` попробуйте метод `Last` из `System.Linq`

2020-08-28 16:59 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +            ShowList<RecipeIngredient>(recipeListOfCategory[i - 1].Ingredients);
У Вас дублирование кода

2020-09-01 15:43 UTC, alex-geraschenko requested changes

2020-09-01 15:43 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.BL/Model/Recipe.cs
> +        [JsonIgnore]
Айди лучше не игнорировать, а записывать. А игнорировать как раз свойство `Category`, т.к. его можно восстановить из другого репозитория по айди.
```
public int CategoryId { get; set; }

[JsonIgnore]
public RecipeBookCategory Category { get; set; }
```

2020-09-01 15:43 UTC, alex-geraschenko commented on RecipeBook/RecipeBook.ConsoleInterface/Manager.cs
> +            foodProductList = (foodProductController.GetAllItems()).ToList();
Дополнительные скобки не нужны, достаточно будет `foodProductController.GetAllItems().ToList();`. Тоже касается и `categories`

2020-09-01 15:43 UTC, alex-geraschenko commented on RecipeBook/categories.json
> +    "ListOfSubcategories": [
Хранить список подкатегорий не эффективно. Лучше применить плоскую структуру с `ParentId` https://stackoverflow.com/questions/9409021/id-parentid-list-to-hierarchical-list

2020-09-02 17:18 UTC, alex-geraschenko requested changes
В целом хорошо. Можно мержить

2020-09-02 17:18 UTC, alex-geraschenko approved these changes, later dismissed

2020-09-02 17:20 UTC, alex-geraschenko approved these changes
В целом хорошо. Можно мержить

2020-09-03 09:13 UTC, merged